# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='edit_token',
            field=models.CharField(max_length=64),
        ),
    ]
